export const posts = [
  {
    slug: "campaign-preview-update",
    title: "Campaign preview update",
    author: "Aisha",
    authorRole: "Marketing Lead",
    type: "post",
    department: "marketing",
    channel: "campaign-launches",
    time: "35 minutes ago",
    summary:
      "We’ve uploaded the first draft of the summer campaign preview. Feedback is welcome before the review session tomorrow.",
    content:
      "We’ve uploaded the first draft of the summer campaign preview. The current version includes the revised hero layout, updated color treatment, and a first pass on gallery imagery. Please review the overall direction before the internal review session tomorrow afternoon.",
    reactions: "18 likes",
    commentsCount: 6,
    attachment: "campaign-preview-v2.fig",
    comments: [
      {
        author: "Naavil",
        role: "Product Designer",
        text: "The hierarchy feels much stronger now. The first visual block reads much better.",
        time: "22 minutes ago",
      },
      {
        author: "Ibrahim",
        role: "Frontend Engineer",
        text: "I think the compact card treatment would fit this direction nicely.",
        time: "18 minutes ago",
      },
      {
        author: "Sara",
        role: "HR Manager",
        text: "This looks clean. The gallery section will help the demo feel fuller too.",
        time: "11 minutes ago",
      },
    ],
  },
  {
    slug: "dashboard-layout-refresh",
    title: "Dashboard layout refresh",
    author: "Ibrahim",
    authorRole: "Frontend Engineer",
    type: "post",
    department: "engineering",
    channel: "frontend",
    time: "1 hour ago",
    summary:
      "The dashboard layout mock has been updated with better hierarchy and more breathing room. Please check the latest build.",
    content:
      "The dashboard layout mock has been updated with a more compact sidebar, cleaner content spacing, and contextual secondary menus for departments and direct messages. The goal was to improve organization while reducing the feeling of density across the UI.",
    reactions: "24 likes",
    commentsCount: 9,
    attachment: "layout-adjustments.tsx",
    comments: [
      {
        author: "Naavil",
        role: "Product Designer",
        text: "The smaller nav density is definitely better. The department submenu feels more controlled now.",
        time: "47 minutes ago",
      },
      {
        author: "Aisha",
        role: "Marketing Lead",
        text: "This feels much easier to scan.",
        time: "33 minutes ago",
      },
    ],
  },
  {
    slug: "monthly-budget-summary",
    title: "Monthly budget summary",
    author: "Finance Team",
    authorRole: "Department Team",
    type: "post",
    department: "finance",
    channel: "budget-updates",
    time: "3 hours ago",
    summary: "The monthly budget summary is now available for department heads. Approval reviews begin this afternoon.",
    content:
      "The latest monthly budget summary is now available for review. Department heads should check the updated category allocations and confirm pending approval items before this afternoon’s review window closes.",
    reactions: "11 likes",
    commentsCount: 4,
    attachment: "budget-summary-q3.xlsx",
    comments: [
      {
        author: "Riyaz",
        role: "Finance Analyst",
        text: "Please focus on the updated cost allocation notes in section three.",
        time: "2 hours ago",
      },
    ],
  },
  {
    slug: "leave-policy-update",
    title: "Updated leave policy published",
    author: "HR",
    authorRole: "Official Notice",
    type: "announcement",
    department: "hr",
    channel: "policy-updates",
    time: "2 hours ago",
    summary: "Employees are encouraged to review the revised annual leave and emergency leave policy by Friday.",
    content:
      "The updated annual leave and emergency leave policy has now been published. Employees should review the revised eligibility notes, updated approval process, and clarified scheduling guidance before Friday.",
    reactions: "32 acknowledgments",
    commentsCount: 3,
    attachment: "leave-policy-summary.pdf",
    comments: [
      {
        author: "Sara",
        role: "HR Manager",
        text: "Please direct questions to HR before the weekly policy session.",
        time: "1 hour ago",
      },
    ],
  },
  {
    slug: "remote-work-guidance-refresh",
    title: "Remote work guidance refreshed",
    author: "HR",
    authorRole: "Official Notice",
    type: "announcement",
    department: "hr",
    channel: "policy-updates",
    time: "Yesterday",
    summary: "The hybrid attendance and remote work guidance has been updated for department managers.",
    content:
      "The remote work and hybrid attendance guidance has been refreshed. Department managers should review the updated scheduling notes and escalation guidelines for attendance exceptions.",
    reactions: "14 acknowledgments",
    commentsCount: 2,
    attachment: "remote-work-guidance.pdf",
    comments: [
      {
        author: "Naavil",
        role: "Product Designer",
        text: "The manager-specific clarification is much clearer now.",
        time: "Yesterday",
      },
    ],
  },
  {
    slug: "engineering-release-summary",
    title: "Dashboard shell v2 deployed to mock demo",
    author: "Engineering",
    authorRole: "Release Notes",
    type: "post",
    department: "engineering",
    channel: "release-notes",
    time: "Today",
    summary: "The updated layout structure, compact sidebar, and route-aware submenus are now in the latest build.",
    content:
      "The latest demo build now includes a compacted navigation system, contextual submenus for departments and direct messages, and improved spacing across the interface. The goal is to make the app more organized and easier to scan.",
    reactions: "16 likes",
    commentsCount: 5,
    attachment: "release-summary-v2.md",
    comments: [
      {
        author: "Ibrahim",
        role: "Frontend Engineer",
        text: "This release mainly focused on navigation and density improvements.",
        time: "Today",
      },
    ],
  },
  {
    slug: "creative-review-deck-uploaded",
    title: "Creative review deck uploaded",
    author: "Marketing",
    authorRole: "Creative Review",
    type: "post",
    department: "marketing",
    channel: "creative-review",
    time: "Today",
    summary: "The latest internal creative review deck is now available for feedback.",
    content:
      "The latest internal creative review deck has been uploaded and is ready for comments before tomorrow’s review. Focus areas include visual consistency, campaign sequencing, and mobile presentation hierarchy.",
    reactions: "13 likes",
    commentsCount: 4,
    attachment: "creative-review-deck.pdf",
    comments: [
      {
        author: "Aisha",
        role: "Marketing Lead",
        text: "Please focus on slide flow and visual consistency.",
        time: "Today",
      },
    ],
  },
];

export const notifications = [
  {
    id: 1,
    type: "comment",
    title: "Aisha commented on Campaign preview update",
    description: "The hierarchy feels much stronger now. The first visual block reads much better.",
    time: "12 minutes ago",
    unread: true,
    href: "/posts/campaign-preview-update",
  },
  {
    id: 2,
    type: "announcement",
    title: "HR published Updated leave policy",
    description: "Employees are encouraged to review the revised annual leave and emergency leave policy by Friday.",
    time: "28 minutes ago",
    unread: true,
    href: "/posts/leave-policy-update",
  },
  {
    id: 3,
    type: "message",
    title: "You received a direct message from Sara",
    description: "Please check the onboarding poll draft.",
    time: "1 hour ago",
    unread: true,
    href: "/messages/sara",
  },
  {
    id: 4,
    type: "channel",
    title: "New activity in #frontend",
    description: "Ibrahim posted Dashboard layout refresh in Engineering.",
    time: "1 hour ago",
    unread: false,
    href: "/departments/engineering/frontend",
  },
  {
    id: 5,
    type: "poll",
    title: "Poll update: What time should the Q2 town hall start?",
    description: "9 votes so far. Public vote details are visible in the poll.",
    time: "2 hours ago",
    unread: false,
    href: "/polls",
  },
  {
    id: 6,
    type: "reaction",
    title: "Naavil reacted to Dashboard layout refresh",
    description: "Your post received new engagement from the team.",
    time: "3 hours ago",
    unread: false,
    href: "/posts/dashboard-layout-refresh",
  },
  {
    id: 7,
    type: "channel",
    title: "New activity in #policy-updates",
    description: "Remote work guidance refreshed was posted in HR.",
    time: "Yesterday",
    unread: false,
    href: "/departments/hr/policy-updates",
  },
  {
    id: 8,
    type: "message",
    title: "You received a direct message from Ibrahim",
    description: "I pushed the updated layout adjustments.",
    time: "Yesterday",
    unread: false,
    href: "/messages/ibrahim",
  },
];
